STATE op_ipush(STACK* stack, STREAM* program, STATE vm);
STATE op_iadd(STACK* stack, STREAM* program, STATE vm);
STATE op_isub(STACK* stack, STREAM* program, STATE vm);
STATE op_imul(STACK* stack, STREAM* program, STATE vm);
STATE op_idiv(STACK* stack, STREAM* program, STATE vm);
STATE op_iand(STACK* stack, STREAM* program, STATE vm);
STATE op_inot(STACK* stack, STREAM* program, STATE vm);
STATE op_ixor(STACK* stack, STREAM* program, STATE vm);
STATE op_ior(STACK* stack, STREAM* program, STATE vm);